version: "3"
services:
    laravel:
        build:
            context: ./
            dockerfile: laravel.dockerfile
        image: laravel
        ports:
            - 8000:8000
        expose:
            - 8000
        volumes:
            - ./backend:/var/www/html
            - app-laravel:/var/www/html/vendor
        networks:
            - app
        command: 
            - bash
            - -c
            - | 
                composer install
                php artisan migrate
                php artisan serve --host=0.0.0.0
        stop_grace_period: 1s
        depends_on:
            - redis
            - pgsql
        healthcheck:
            test: 
                - CMD
                - curl
                - --fail
                - http://localhost:8000
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        expose:
            - 6379
        networks:
            - app
        healthcheck:
            test: 
                - CMD
                - redis-cli
                - ping
                - '|'
                - grep
                - PONG
            retries: 3
            timeout: 5s

    next:
        image: node:slim
        ports:
            - 3000:3000
        expose:
            - 3000
        working_dir: /usr/src/app
        environment:
            - WATCHPACK_POLLING=true
        volumes:
            - ./frontend:/usr/src/app
            - app-next:/usr/src/app/node_modules
        networks:
            - app
        command: 
            - bash 
            - -c 
            - |
                npm i
                npm run dev
        stop_grace_period: 1s
        healthcheck:
            test: 
                - CMD
                - curl
                - --fail
                - http://localhost:3000
            retries: 3
            timeout: 5s    
    
    pgsql:
        image: postgres:16.1
        ports:
            - 5432:5432
        env_file:
            - .env
        expose:
            - 5432
        volumes:
            - app-pgsql:/var/lib/postgresql/data
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - pg_isready
            retries: 3
            timeout: 5s

networks:
    app:
        driver: bridge

volumes:
    app-redis:
        driver: local
    app-next:
        driver: local
    app-laravel:
        driver: local
    app-pgsql:
        driver: local